### ISSUE TITLE
[2020.09.17 (목)] 박성아의 문제

### ISSUE THREAD

**Issue by parkseonga** [Doyun-lab/A-group-of-people-to-succeed#6]
1081 : [기초-종합] 주사위를 2개 던지면?(설명) - https://codeup.kr/problem.php?id=1081

1228 : 비만도 측정 - https://codeup.kr/problem.php?id=1228

1096 : [기초-2차원배열] 바둑판에 흰 돌 놓기(설명) - https://codeup.kr/problem.php?id=1096

기간 : 2020-09-17 23:59

**Comment by parkseonga** [comment]
```
array = [[0]*3]*3
array[0][1] = 1
array
```
위 코드를 입력했을 때 

 [[0, 1, 0], [0, 1, 0], [0, 1, 0]]  이렇게 출력이 되는데 

맨 처음 리스트의 두번째값만 바뀌게 하려면 어떻게 해야되는지 아실까요?

@pmsk98 @qudgns5129  @Doyun-lab

**Comment by Doyun-lab** [comment]
왜 그럴까요 ~

@parkseonga

**Comment by qudgns5129** [comment]
> ```
> array = [[0]*3]*3
> array[0][1] = 1
> array
> ```
> 
> 위 코드를 입력했을 때
> 
> [[0, 1, 0], [0, 1, 0], [0, 1, 0]] 이렇게 출력이 되는데
> 
> 맨 처음 리스트의 두번째값만 바뀌게 하려면 어떻게 해야되는지 아실까요?
> 
> @pmsk98 @qudgns5129 @Doyun-lab

이거 array[0][1] 말고 for문 사용하셔서 [[0 for i in range(3)] for j in range(3)] 이런식으로 선언을 해야합니다.  
지금 명석씨가 하신 방식대로 한다면 array의 0번 째 인덱스와 1번 째 인덱스와 2번 째 인덱스는 동일한 주소를 참조합니다. (이 부분에 대해서는 확인해보지 않았지만 추정(id함수로 확인해보시면 좋을거 같아요!))  
동일한 주소를 가지고 있어서 array[0][1]에 1을 넣어주시면 다른 인덱스의 2번째 요소도 바뀌는 거에요!

**Comment by qudgns5129** [comment]
리스트 곱 연산으로 선언하는 것보다 for문을 사용하여 만드는 것이 더 나아보입니다!

**Comment by parkseonga** [comment]
@qudgns5129  감사합니다!!!
