### ISSUE TITLE
[2020.09.18 (금)] 김병훈의 문제

### ISSUE THREAD

**Issue by qudgns5129** [Doyun-lab/A-group-of-people-to-succeed#7]
1170 : 당신의 학번은? 1 - https://codeup.kr/problem.php?id=1170

1267 : n개의 수 중 5의 배수의 합 - https://codeup.kr/problem.php?id=1267

1093 : 이상한 출석 번호 부르기1 - https://codeup.kr/problem.php?id=1093
  
기간 : 2020-09-18 23:59

**Comment by Doyun-lab** [comment]
다음주부터 월, 화, 수, 목 합시다 ~ 순서는 똑같이

@parkseonga @pmsk98 @qudgns5129
